import Head from 'next/head'
import Form from '../components/Form'
import { useState } from 'react'
import QRCode from "react-qr-code";
import axios from 'axios';
import { Upload } from '../components/Upload';

export default function Home() {

  const [formData, setFormData] = useState({ name: '', email: '',phone: '', title: ''});
  const [openWindow, setOpenWindow] = useState(1);
  const [imageUrl, setImageUrl] = useState('');

  const qrData = `BEGIN:VCARD
N:${formData.name};
TEL;TYPE=work,VOICE:${formData.phone}
EMAIL:${formData.email}
ORG:BILESIM FINANSAL TEKNOLOJILER VE ODEME SISTEMLERI
TITLE:${formData.title}
VERSION:3.0
END:VCARD`

  const getTextAnnotations = async (url) => {
    try {
      const response = await axios.post(
        `${process.env.NEXT_PUBLIC_AZURE}/api/image?image=${url}`
      );
      console.log(response);
      return response.data.textContent[0].split("\n")
    } catch (err) {
      console.error(err);
      return ["error", err]
    }
  };

  const handleImageUrlInput = e => setImageUrl(e.target.value);
  
  const handleImageUrlSubmit = async (e) => {
    e.preventDefault();
    const textAnnotations = await getTextAnnotations(imageUrl);
    console.log(textAnnotations);
    setFormData((prevFormData) => {
      return {
        ...prevFormData,
        name: textAnnotations[2],
        email: textAnnotations[7],
        title: `${textAnnotations[3]} - ${textAnnotations[4]}`,
      }
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {
      openWindow === 1
      ?
      <Form formData={formData} setFormData={setFormData} setOpenWindow={setOpenWindow} />
      :
      <button className="fixed p-10 bg-blue-500 bottom-10" onClick={() => setOpenWindow(1)} >form</button>
      }

      <form onSubmit={handleImageUrlSubmit}>
        <input id='imageurl' type='imageurl' name='imageurl' placeholder='image url' onChange={handleImageUrlInput} value={imageUrl}/>
        <button type='submit'>GET TEXT FROM IMAGE</button>
      </form>

      <div className="m-10">
        <QRCode value={qrData} />
      </div>
      <Upload handleImageUrlSubmit={handleImageUrlSubmit} />
    </>
  )
}

// BEGIN:VCARD
// N:${formData.name};
// TEL;TYPE=work,VOICE:${formData.phone}
// TEL;TYPE=home,VOICE:(404) 386-1017
// TEL;TYPE=fax:(866) 408-1212
// EMAIL:${formData.email}
// ORG:Smith Designs LLC
// TITLE:Lead Designer
// ADR;TYPE=WORK,PREF:;;151 Moore Avenue;Grand Rapids;MI;49503;United States of America
// URL:https://www.smithdesigns.com
// VERSION:3.0
// END:VCARD
