import Head from 'next/head'
import Form from '../components/Form'
import { useState } from 'react'
import QRCode from "react-qr-code";

export default function Home() {
  
  const [formData, setFormData] = useState({ name: '', email: '',phone: '', })

  const qrData = `BEGIN:VCARD VERSION:3.0 N:Ow123en;Sean;;; FN:Sean Owen TITLE:Software Engineer EMAIL;TYPE=INTERNET;TYPE=WORK;TYPE=PREF:srowen@google.com URL;TYPE=Homepage:https://example.com END:VCARD`

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form formData={formData} setFormData={setFormData} />
      <QRCode value={qrData} />
    </>
  )
}



