import Head from 'next/head'
import Form from '../components/Form'
import { useState } from 'react'
import QRCode from "react-qr-code";

export default function Home() {
  
  const [formData, setFormData] = useState({ name: '', email: '',phone: '', })
  const [openWindow, setOpenWindow] = useState(1)

  const qrData = `BEGIN:VCARD
N:${formData.name};
TEL;TYPE=work,VOICE:${formData.phone}
EMAIL:${formData.email}
ORG:Bileşim A.Ş.
TITLE:Lead Dev
VERSION:3.0
END:VCARD`

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {
      openWindow === 1
      ?
      <Form formData={formData} setFormData={setFormData} setOpenWindow={setOpenWindow} />
      :
      <button className="fixed bottom-10 bg-blue-500 p-10" onClick={() => setOpenWindow(1)} >form</button>
      }

      <div className="m-10">
        <QRCode value={qrData} />
      </div>
    </>
  )
}



// BEGIN:VCARD
// N:${formData.name};
// TEL;TYPE=work,VOICE:${formData.phone}
// TEL;TYPE=home,VOICE:(404) 386-1017
// TEL;TYPE=fax:(866) 408-1212
// EMAIL:${formData.email}
// ORG:Smith Designs LLC
// TITLE:Lead Designer
// ADR;TYPE=WORK,PREF:;;151 Moore Avenue;Grand Rapids;MI;49503;United States of America
// URL:https://www.smithdesigns.com
// VERSION:3.0
// END:VCARD
